#define PERMISSIVE_HOLD_PER_KEY

#define TAPPING_TERM_PER_KEY

#define QUICK_TAP_TERM_PER_KEY

#define ACHORDION_STREAK

#define RETRO_TAPPING
#define RETRO_TAPPING_PER_KEY
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL

