alias e='exit'
alias ls='ls --color=auto'
alias ll='ls -la'
alias ref='exec zsh'

alias ga='git add'
alias gaa='git add *'
alias gd='git diff'
alias gs='git status'
alias gc='git commit -m'
alias gps='git push'
alias gpl='git pull'
alias gr='git remote'
alias gch='git checkout'
alias gb='git branch'
alias gl='git log'
